package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CoursePdfAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePdfAllPropertiesEquals(CoursePdf expected, CoursePdf actual) {
        assertCoursePdfAutoGeneratedPropertiesEquals(expected, actual);
        assertCoursePdfAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePdfAllUpdatablePropertiesEquals(CoursePdf expected, CoursePdf actual) {
        assertCoursePdfUpdatableFieldsEquals(expected, actual);
        assertCoursePdfUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePdfAutoGeneratedPropertiesEquals(CoursePdf expected, CoursePdf actual) {
        assertThat(actual)
            .as("Verify CoursePdf auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePdfUpdatableFieldsEquals(CoursePdf expected, CoursePdf actual) {
        assertThat(actual)
            .as("Verify CoursePdf relevant properties")
            .satisfies(a -> assertThat(a.getLectureUrl()).as("check lectureUrl").isEqualTo(expected.getLectureUrl()))
            .satisfies(a -> assertThat(a.getTasksUrl()).as("check tasksUrl").isEqualTo(expected.getTasksUrl()))
            .satisfies(a -> assertThat(a.getTests()).as("check tests").isEqualTo(expected.getTests()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoursePdfUpdatableRelationshipsEquals(CoursePdf expected, CoursePdf actual) {
        // empty method
    }
}
